---
prometheus_web_listen_address: "0.0.0.0:9090"
prometheus_web_external_url: 'http://prometheus.big.opsta.in.th'

prometheus_global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

prometheus_scrape_configs:
  - job_name: "prometheus"
    metrics_path: "{{ prometheus_metrics_path }}"
    static_configs:
      - targets:
          - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9090"
  - job_name: 'develop'
    scrape_interval: 30s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job="kube-state-metrics"}'
        - '{job="kubelet"}'
        - '{job="kubernetes-service-endpoints"}'
        # - '{job="service-postgres"}'
        # - '{job="service-rabbitmq"}'
        # - '{job="service-redis"}'
        # - '{job="service-elasticsearch"}'
        # - '{job="opstella-blackbox"}'
    static_configs:
      - targets:
        - 'prometheus.develop.cluster.big.opsta.in.th'
        labels:
          env: dev
          project: opsta-monitoring
          type: dev
          hostname:  prometheus.develop.cluster.big.opsta.in.th
    metric_relabel_configs:
      - source_labels: [job]
        regex: 'kubernetes-service-endpoints'
        action: replace
        target_label: job
        replacement: devops-develop-node-exporter

prometheus_alert_rules: []

prometheus_storage_retention: "1d"
# Available since Prometheus 2.7.0
# [EXPERIMENTAL] Maximum number of bytes that can be stored for blocks. Units
# supported: KB, MB, GB, TB, PB.
prometheus_storage_retention_size: "10GB"