{
 "title": "HAProxy 2 Full",
 "description": "HAProxy with Prometheus data",
 "tags": [
  "haproxy",
  "servers"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(haproxy_process_nbproc,instance)"
    }
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": {
     "query": "label_values(haproxy_backend_status{instance=\"$host\"}, proxy)"
    }
   },
   {
    "name": "frontend",
    "label": "Frontend",
    "query": {
     "query": "label_values(haproxy_frontend_status{instance=\"$host\"}, proxy)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(haproxy_server_status{instance=\"$host\"}, server)"
    }
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": {
     "query": "label_values(haproxy_server_http_responses_total{instance=\"$host\"}, code)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Basic General Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "All HTTP responses",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "- back / + front" }
     ],
     "targets": [
      {
       "expr": "sum(rate(haproxy_frontend_http_responses_total{proxy=~\"$frontend\",code=~\"$code\",instance=\"$host\"}[$__rate_interval])) by (code)",
       "legendFormat": "Front {{ code }}"
      },
      {
       "expr": "sum(rate(haproxy_backend_http_responses_total{proxy=~\"$backend\",code=~\"$code\",instance=\"$host\"}[$__rate_interval])) by (code)",
       "legendFormat": "Back {{ code }}"
      }
     ]
    },
    {
     "title": "Incoming / Outgoing bytes",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bits", "label": "- out / + in" }
     ],
     "targets": [
      {
       "expr": "sum(rate(haproxy_frontend_bytes_in_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])*8) by (instance)",
       "legendFormat": "IN Front"
      },
      {
       "expr": "sum(rate(haproxy_frontend_bytes_out_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])*8) by (instance)",
       "legendFormat": "OUT Front"
      },
      {
       "expr": "sum(rate(haproxy_backend_bytes_in_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])*8) by (instance)",
       "legendFormat": "IN Back"
      },
      {
       "expr": "sum(rate(haproxy_backend_bytes_out_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])*8) by (instance)",
       "legendFormat": "OUT Back"
      }
     ]
    },
    {
     "title": "Number of connections",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "- back / + front" }
     ],
     "targets": [
      {
       "expr": "sum(rate(haproxy_frontend_connections_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Front"
      },
      {
       "expr": "sum(rate(haproxy_backend_connection_errors_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Back errors"
      }
     ]
    },
    {
     "title": "Requests and Responses",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "- back / + front" }
     ],
     "targets": [
      {
       "expr": "sum(rate(haproxy_frontend_http_requests_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Front requests"
      },
      {
       "expr": "sum(rate(haproxy_frontend_request_errors_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Front requests errors"
      },
      {
       "expr": "sum(rate(haproxy_frontend_requests_denied_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Front request denied"
      },
      {
       "expr": "sum(rate(haproxy_backend_redispatch_warnings_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Back redispatch warnings"
      },
      {
       "expr": "sum(rate(haproxy_backend_retry_warnings_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Back retry warnings"
      },
      {
       "expr": "sum(rate(haproxy_backend_response_errors_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Back response errors"
      },
      {
       "expr": "sum(haproxy_backend_current_queue{proxy=~\"$backend\",instance=\"$host\"}) by (instance)",
       "legendFormat": "Back queued requests"
      },
      {
       "expr": "sum(rate(haproxy_backend_http_requests_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Back requests"
      }
     ]
    },
    {
     "title": "Active sessions",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "- back / + front" }
     ],
     "targets": [
      {
       "expr": "sum(rate(haproxy_frontend_current_sessions{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Front"
      },
      {
       "expr": "sum(rate(haproxy_backend_current_sessions{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Back"
      }
     ]
    }
   ]
  },
  {
   "title": "Basic General Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Status",
     "type": "graph",
     "gridPos": { "h": 4, "w": 22, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short", "label": "- back / + front" }
     ],
     "targets": [
      {
       "expr": "count(haproxy_frontend_status{instance=\"$host\"} == 1)",
       "legendFormat": "Front Up"
      },
      {
       "expr": "count(haproxy_backend_status{instance=\"$host\"} ==1)",
       "legendFormat": "Back Up"
      }
     ]
    },
    {
     "title": "Started...",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 22, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - haproxy_process_start_time_seconds{instance=\"$host\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Throughtput / Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front - Incoming / Outgoing bytes",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "bits", "label": "- out / + in" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_frontend_bytes_in_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "IN {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_frontend_bytes_out_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "OUT {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Incoming / Outgoing bytes",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "bits", "label": "- out / + in" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_backend_bytes_in_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "IN {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_backend_bytes_out_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "OUT {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Connections successful / denied",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short", "label": "- denied / + successful" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_frontend_connections_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Successful {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_frontend_denied_connections_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Connections attempts / errors",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short", "label": "- error / + attempt" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_backend_connection_attempts_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Attempts {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_backend_connection_errors_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Error {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Maximum observed number of connections per second",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short", "label": "connections" }
     ],
     "targets": [
      {
       "expr": "haproxy_frontend_connections_rate_max{proxy=~\"$frontend\",instance=\"$host\"}",
       "legendFormat": "Max {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Connections reuses",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short", "label": "reuses" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_backend_connection_reuses_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Reuses {{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Back - Queued requests not assigned to any server",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short", "label": "requests" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_current_queue{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "Queued {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Max queued requests not assigned to any server",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short", "label": "requests" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_max_queue{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "Max {{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests / Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Back - HTTP requests OK / Denied",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short", "label": "- denied / + ok" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_backend_http_requests_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_backend_requests_denied_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - HTTP requests OK / Error / Denied",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short", "label": "- error - denied / + ok" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_frontend_http_requests_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_frontend_request_errors_total{proxy=~\"$frontend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Error {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_frontend_requests_denied_total{proxy=~\"$frontend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - HTTP responses denied",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "denied" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_backend_responses_denied_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - HTTP responses denied",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "denied" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_frontend_responses_denied_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Error / Redispatch / Retry",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short", "label": "- error / + redispatch + retry" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_backend_redispatch_warnings_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Redispatch {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_backend_retry_warnings_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Retry {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_backend_response_errors_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Error {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Maximum observed number of HTTP requests per second",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short", "label": "requests" }
     ],
     "targets": [
      {
       "expr": "haproxy_frontend_http_requests_rate_max{proxy=~\"$frontend\", instance=\"$host\"}",
       "legendFormat": "Max {{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Back - Avg connection time",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_connect_time_average_seconds{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Max connection time",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_max_connect_time_seconds{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Avg. total time",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_total_time_average_seconds{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Max total time",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_max_total_time_seconds{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Avg. response time",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_response_time_average_seconds{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Max response time",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_max_response_time_seconds{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Avg. queue time for last 1024 successful connections",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_queue_time_average_seconds{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Max queue time",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_max_queue_time_seconds{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Responses by HTTP code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front - HTTP responses code",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short", "label": "responses" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_frontend_http_responses_total{proxy=~\"$frontend\", code=~\"$code\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ code }} {{ proxy }} "
      }
     ]
    },
    {
     "title": "Back - HTTP responses code",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short", "label": "responses" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_backend_http_responses_total{proxy=~\"$backend\", code=~\"$code\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ code }} {{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - HTTP responses code",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_http_responses_total{proxy=~\"$backend\",server=~\"$server\",code=~\"$code\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ code }} {{ proxy }} {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front - Number of sessions",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short", "label": "- denied / + total" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_frontend_sessions_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_frontend_denied_sessions_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Number of sessions",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short", "label": "total" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_backend_sessions_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Maximum observed number of active sessions and limit",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "sessions" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_max_sessions{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "Max {{ proxy }}"
      },
      {
       "expr": "haproxy_backend_limit_sessions{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "Limit {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Maximum observed number of active sessions and limit",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "sessions" }
     ],
     "targets": [
      {
       "expr": "haproxy_frontend_max_sessions{proxy=~\"$frontend\",instance=\"$host\"}",
       "legendFormat": "Max {{ proxy }}"
      },
      {
       "expr": "haproxy_frontend_limit_sessions{proxy=~\"$frontend\",instance=\"$host\"}",
       "legendFormat": "Limit {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Maximum observed number of sessions per second",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short", "label": "sessions" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_max_session_rate{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "Max {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Maximum observed number of sessions per second and limit",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short", "label": "sessions" }
     ],
     "targets": [
      {
       "expr": "haproxy_frontend_max_session_rate{proxy=~\"$frontend\",instance=\"$host\"}",
       "legendFormat": "Max {{ proxy }}"
      },
      {
       "expr": "haproxy_frontend_limit_session_rate{proxy=~\"$frontend\",instance=\"$host\"}",
       "legendFormat": "Limit {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Failed header rewriting warnings",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short", "label": "sessions" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_backend_failed_header_rewriting_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Failed header rewriting warnings",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "short", "label": "sessions" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_frontend_failed_header_rewriting_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back -  Last session assigned",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_backend_last_session_seconds{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Maximum observed number of HTTP requests per second",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_frontend_http_requests_rate_max{proxy=~\"$frontend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back -  Data transfers aborted",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "s", "label": "- server / + client" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_backend_client_aborts_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "By client {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_backend_server_aborts_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "By server {{ proxy }}"
      }
     ]
    },
    {
     "title": "Server -  Data transfers aborted",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_client_aborts_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "By client {{ proxy }} / {{ server }}"
      },
      {
       "expr": "haproxy_server_server_aborts_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "By server {{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Health and Weight",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Back - UP->DOWN transitions",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 301 },
     "yaxes": [
      { "format": "short", "label": "transitions" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_backend_check_up_down_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Service weight",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 301 },
     "yaxes": [
      { "format": "short", "label": "weight" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_weight{proxy=~\"$backend\", instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache / Compressor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front - Cache lookups / hits",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 302 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_frontend_http_cache_lookups_total{proxy=~\"$frontend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Lookups {{ proxy }} "
      },
      {
       "expr": "rate(haproxy_frontend_http_cache_hits_total{proxy=~\"$frontend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Hits {{ proxy }} "
      }
     ]
    },
    {
     "title": "Back - Cache lookups / hits",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 302 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_backend_http_cache_lookups_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Lookups {{ proxy }} "
      },
      {
       "expr": "rate(haproxy_backend_http_cache_hits_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Hits {{ proxy }} "
      }
     ]
    },
    {
     "title": "Front - Compressor",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 313 },
     "yaxes": [
      { "format": "bytes", "label": "- emitted / + bypasses + fed" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_frontend_http_comp_bytes_in_total{proxy=~\"$frontend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Bytes fed {{ proxy }} "
      },
      {
       "expr": "rate(haproxy_frontend_http_comp_bytes_out_total{proxy=~\"$frontend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Bytes emitted {{ proxy }} "
      },
      {
       "expr": "rate(haproxy_frontend_http_comp_bytes_bypassed_total{proxy=~\"$frontend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Bytes bypassed  {{ proxy }} "
      }
     ]
    },
    {
     "title": "Back - Compressor",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 313 },
     "yaxes": [
      { "format": "bytes", "label": "- emitted / + bypasses + fed" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_backend_http_comp_bytes_in_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Bytes fed {{ proxy }} "
      },
      {
       "expr": "rate(haproxy_backend_http_comp_bytes_out_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Bytes emitted {{ proxy }} "
      },
      {
       "expr": "rate(haproxy_backend_http_comp_bytes_bypassed_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Bytes bypassed  {{ proxy }} "
      }
     ]
    },
    {
     "title": "Front - Responses compressed",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 324 },
     "yaxes": [
      { "format": "short", "label": "responses" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_frontend_http_comp_responses_total{proxy=~\"$frontend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} "
      }
     ]
    },
    {
     "title": "Back - Responses compressed",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 324 },
     "yaxes": [
      { "format": "short", "label": "responses" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_backend_http_comp_responses_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} "
      }
     ]
    }
   ]
  },
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front - Status",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 303 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "haproxy_frontend_status{proxy=~\"$frontend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Status",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 303 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_status{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Active servers",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 314 },
     "yaxes": [
      { "format": "short", "label": "- backup / + active" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_active_servers{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Backup servers",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 314 },
     "yaxes": [
      { "format": "short", "label": "- backup / + active" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_backup_servers{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By server - Throughtput  / Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Incoming / Outgoing bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 304 },
     "yaxes": [
      { "format": "bits", "label": "- out / + in" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_bytes_in_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "IN {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(haproxy_server_bytes_out_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "OUT {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Connections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 312 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_current_sessions{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "In use {{ proxy }} / {{ server }}{{ proxy }}"
      },
      {
       "expr": "rate(haproxy_server_server_idle_connections_current{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Estimated {{ proxy }} / {{ server }}{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Connections attempts / error",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 321 },
     "yaxes": [
      { "format": "short", "label": "- error / + attempts" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_connection_attempts_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Attempts {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(haproxy_server_connection_errors_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Error {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Number of connections reuses",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 329 },
     "yaxes": [
      { "format": "short", "label": "reuses" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_connection_reuses_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Reuses {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Idle connections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 338 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_server_idle_connections_current{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Available idle connections {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(haproxy_server_server_idle_connections_limit{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Limit available idle connections {{ proxy }} / {{ server }}{{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By server - Requests / Responses / Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - HTTP responses denied",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 417 },
     "yaxes": [
      { "format": "short", "label": "denied" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_responses_denied_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Denied {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Error / Redispatch / Retry",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 426 },
     "yaxes": [
      { "format": "short", "label": "- error / + redispatch + retry" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_redispatch_warnings_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Redispatch {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(haproxy_server_retry_warnings_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Retry {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(haproxy_server_response_errors_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Error {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Queued requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 433 },
     "yaxes": [
      { "format": "short", "label": "requests" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_current_queue{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Current {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Max  queued requests and limit",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 440 },
     "yaxes": [
      { "format": "short", "label": "requests" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_max_queue{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "Max {{ proxy }} / {{ server }}"
      },
      {
       "expr": "haproxy_server_queue_limit{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "Limit {{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By server - Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Average connection time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 448 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_connect_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Max connection time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 455 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_max_connect_time_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Average response time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 462 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_response_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Max response time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 469 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_max_response_time_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Average total time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 476 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_total_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Max total time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 484 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_max_total_time_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Average queue time for last 1024 successful connections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 493 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_queue_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Max queue time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 502 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_max_queue_time_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By server - Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Number of active sessions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 449 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_sessions_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total {{ proxy }} / {{ server }}"
      },
      {
       "expr": "haproxy_server_limit_sessions{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "Limit {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Failed header rewriting warnings",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 457 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_failed_header_rewriting_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} /  {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Number of sessions per second and limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 466 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_max_session_rate{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "Rate {{ proxy }} / {{ server }}"
      },
      {
       "expr": "haproxy_server_limit_session_rate{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "Limit {{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By server - Health and Weight",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Service weight",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 450 },
     "yaxes": [
      { "format": "none", "label": "weight" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_weight{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - UP->DOWN transitions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 458 },
     "yaxes": [
      { "format": "none", "label": "transitions" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_check_up_down_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Checks failures",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 466 },
     "yaxes": [
      { "format": "none", "label": "failures" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_check_failures_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server -Throttle percentage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 477 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_current_throttle{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Number of seconds since last session assigned to server/backend",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 487 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_server_last_session_seconds{proxy=~\"$backend\", server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By server - Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 451 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "haproxy_server_status{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Failed DNS resolutions",
     "type": "graph",
     "description": "Number of failed DNS resolutions in current worker process since started",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 459 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_process_failed_resolutions{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Failed"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Connections / Sessions / Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process - Sessions over last second",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 598 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_current_session_rate{instance=\"$host\"}",
       "legendFormat": "Current number of sessions per second over last elapsed second"
      },
      {
       "expr": "haproxy_process_limit_session_rate{instance=\"$host\"}",
       "legendFormat": "Configured maximum number of sessions per second"
      }
     ]
    },
    {
     "title": "Process - Total sessions / requests",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 598 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_process_connections_total{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total number of created sessions"
      },
      {
       "expr": "rate(haproxy_process_requests_total{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total number of requests (TCP or HTTP)"
      }
     ]
    },
    {
     "title": "Process - Connections over last second",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 612 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_current_connection_rate{instance=\"$host\"}",
       "legendFormat": "Current number of connections per second over last elapsed second"
      },
      {
       "expr": "haproxy_process_limit_connection_rate{instance=\"$host\"}",
       "legendFormat": "Configured maximum number of connections per second."
      }
     ]
    },
    {
     "title": "Process - Max connections",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 612 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_max_connections{instance=\"$host\"}",
       "legendFormat": "Maximum number of concurrent connections"
      },
      {
       "expr": "haproxy_process_hard_max_connections{instance=\"$host\"}",
       "legendFormat": "Initial Maximum number of concurrent connections"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Compression",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process - Compression memory",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 627 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_current_zlib_memory{instance=\"$host\"}",
       "legendFormat": "Current memory used for zlib in bytes"
      },
      {
       "expr": "haproxy_process_max_zlib_memory{instance=\"$host\"}",
       "legendFormat": "Configured maximum amount of memory for zlib in bytes"
      }
     ]
    },
    {
     "title": "Process - Compression",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 627 },
     "yaxes": [
      { "format": "short", "label": "- before / + after" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_process_http_comp_bytes_in_total{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Number of bytes per second over last elapsed second, before http compression"
      },
      {
       "expr": "rate(haproxy_process_http_comp_bytes_out_total{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Number of bytes per second over last elapsed second, after http compression"
      },
      {
       "expr": "haproxy_process_limit_http_comp{instance=\"$host\"}",
       "legendFormat": "Configured maximum input compression rate in bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "Process SSL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process - SSL cache",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 628 },
     "yaxes": [
      { "format": "short", "label": "- misses / + lookups" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_process_ssl_cache_lookups_total{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total number of SSL session cache lookups"
      },
      {
       "expr": "rate(haproxy_process_ssl_cache_misses_total{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total number of SSL session cache misses"
      }
     ]
    },
    {
     "title": "Process - SSL key rate",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 628 },
     "yaxes": [
      { "format": "short", "label": "- backend / + frontend" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_current_frontend_ssl_key_rate{instance=\"$host\"}",
       "legendFormat": "Current frontend SSL Key computation per second over last elapsed second"
      },
      {
       "expr": "haproxy_process_current_backend_ssl_key_rate{instance=\"$host\"}",
       "legendFormat": "Current backend SSL Key computation per second over last elapsed second"
      }
     ]
    },
    {
     "title": "Process - SSL rate",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 640 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_current_ssl_rate{instance=\"$host\"}",
       "legendFormat": "Current number of SSL sessions per second over last elapsed second"
      },
      {
       "expr": "haproxy_process_limit_ssl_rate{instance=\"$host\"}",
       "legendFormat": "Configured maximum number of SSL sessions per second"
      }
     ]
    },
    {
     "title": "Process - SSL connections",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 640 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_current_ssl_connections{instance=\"$host\"}",
       "legendFormat": "Current number of opened SSL connections"
      },
      {
       "expr": "haproxy_process_max_ssl_connections{instance=\"$host\"}",
       "legendFormat": "Configured maximum number of concurrent SSL connections"
      }
     ]
    },
    {
     "title": "Process - SSL reuse ratio",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 652 },
     "yaxes": [
      { "format": "percent", "label": "ratio" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_frontend_ssl_reuse{instance=\"$host\"}",
       "legendFormat": "SSL session reuse ratio (percent)"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process - Memory",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 675 },
     "yaxes": [
      { "format": "bytes", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_max_memory_bytes{instance=\"$host\"}",
       "legendFormat": "Per-process memory limit (in bytes); 0=unset"
      },
      {
       "expr": "rate(haproxy_process_pool_allocated_bytes{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total amount of memory allocated in pools (in bytes)"
      },
      {
       "expr": "rate(haproxy_process_pool_used_bytes{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total amount of memory used in pools (in bytes)"
      }
     ]
    },
    {
     "title": "Process - Tasks",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 675 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_process_current_tasks{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Current number of tasks"
      },
      {
       "expr": "haproxy_process_current_run_queue{instance=\"$host\"}",
       "legendFormat": "Current number of tasks in the run-queue"
      },
      {
       "expr": "haproxy_process_stopping{instance=\"$host\"}",
       "legendFormat": "Non zero means stopping in progress"
      }
     ]
    },
    {
     "title": "Process - Maximum open files / sockets",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 688 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_max_fds{instance=\"$host\"}",
       "legendFormat": "Maximum number of open file descriptors; 0=unset"
      },
      {
       "expr": "haproxy_process_max_sockets{instance=\"$host\"}",
       "legendFormat": "Maximum numer of open sockets"
      }
     ]
    },
    {
     "title": "Process - Pipes",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 688 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_max_pipes{instance=\"$host\"}",
       "legendFormat": "Configured maximum number of pipes"
      },
      {
       "expr": "rate(haproxy_process_pipes_used_total{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Number of pipes in used"
      },
      {
       "expr": "rate(haproxy_process_pipes_free_total{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Number of pipes unused"
      }
     ]
    },
    {
     "title": "Process - Configured threads / processes",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 701 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_nbthread{instance=\"$host\"}",
       "legendFormat": "Threads"
      },
      {
       "expr": "haproxy_process_nbproc{instance=\"$host\"}",
       "legendFormat": "Processes"
      }
     ]
    },
    {
     "title": "Process - Pool allocations",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 701 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_pool_failures_total{instance=\"$host\"}",
       "legendFormat": "Total number of failed pool allocations"
      }
     ]
    },
    {
     "title": "Process - Idle",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 714 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_idle_time_percent{instance=\"$host\"}",
       "legendFormat": "Idle to total ratio over last sample (percent)"
      }
     ]
    },
    {
     "title": "Process - Jobs",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 714 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_process_jobs{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Current number of active jobs (listeners, sessions, open devices)"
      },
      {
       "expr": "rate(haproxy_process_unstoppable_jobs{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Current number of active jobs that can't be stopped during a soft stop"
      },
      {
       "expr": "rate(haproxy_process_listeners{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Current number of active listeners"
      }
     ]
    },
    {
     "title": "Process - Peers",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 727 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_active_peers{instance=\"$host\"}",
       "legendFormat": "Current number of active peers"
      },
      {
       "expr": "haproxy_process_connected_peers{instance=\"$host\"}",
       "legendFormat": "Current number of connected peers"
      }
     ]
    },
    {
     "title": "Process - Logs",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 727 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_dropped_logs_total{instance=\"$host\"}",
       "legendFormat": "Total number of dropped logs"
      },
      {
       "expr": "haproxy_process_recv_logs_total{instance=\"$host\"}",
       "legendFormat": "Total number of log messages received by log-forwarding listeners"
      }
     ]
    },
    {
     "title": "Process - Bytes out",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 740 },
     "targets": [
      {
       "expr": "rate(haproxy_process_bytes_out_total{instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "Emitted by current worker {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_process_spliced_bytes_out_total{instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "Emitted by current worker through a kernel pipe {{ proxy }}"
      }
     ]
    },
    {
     "title": "Process - Uptime",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 740 },
     "yaxes": [
      { "format": "s", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_uptime_seconds{instance=\"$host\"}",
       "legendFormat": "How long ago this worker process was started"
      }
     ]
    }
   ]
  }
 ]
}