---
- name: Prepare host
  hosts: all
  become: true

  vars_prompt:
  - name: password
    prompt: "Enter password: "
    private: yes

  tasks:
  - name: Install python lib
    delegate_to: localhost
    pip:
      name:
      - passlib
      - getpass4
  - name: Generate hash pass
    delegate_to: localhost
    command:  python3 -c "from passlib.hash import sha512_crypt; import getpass; print(sha512_crypt.encrypt('{{ password }}'))"
    register: hash
  - debug:
      var: hash.stdout
  - name: Update password
    user:
      name: ubuntu
      password: '{{hash.stdout}}'
    become: yes
